### PR TITLE
[WIP] Add connection manager UIs

### PR DESCRIPTION
**Pull request by dionyziz**
Collaborative work with @sophron. This branch starts an effort to implement #263 with Windows 10 Wifi.

Here's a screenshot of how it looks like so far:

screen shot 2016-06-09 at 12 06 27

Work in progress. Will reiterate on it.

### CODE REVIEW

**Comment by sophron** [comment]
A very nice contribution.

For now we can put some random ESSIDs on the network manager window (among with the ESSID of the target AP of`course).

When we have a mechanism that bridges information from the wireless cards to the templates ready, we will want to put the nearby broadcasted ESSIDs there. I think @lvrach wants to work on this.

**Comment by lvrach** [comment]
@sophron Yeap, I think this is something we should work at our #271.

**Comment by dionyziz** [comment]
Updated with OSX network manager + chrome network problem page.

Screenshot:

screen shot 2016-06-13 at 01 23 14

Top is the fake network manager, bottom is the real network manager.

**Comment by blackHatMonkey** [comment]
@dionyziz This is really great. Keep up the good work. :smile:

**Comment by sophron** [comment]
I merged this. Check #263. Thank you @dionyziz for the great work!

**Pull request closed without merging**
