### PR TITLE
Added support to iOS and Android

### PR DESCRIPTION
**Pull request by alexsalvetti**
Added support to iOS and Android for the wifi_connect page using a javascript prompt pop up.

### CODE REVIEW

**Comment by cicina** [comment]
Hello, great! How can I get this ? Do I need to wait untill wifiphisher 1.3 released?

**Comment by alexsalvetti** [comment]
Hi @sophron I've added the JS pop up discussed in issue #435 
I have tried to keep it simple, on iOS the result it's just amazing because it appears like a system popup but on android it's a little bit more fake with the javascript title. This could be good for iOS but maybe for android we should make an html responsive pop up with a less suspective UI.
Here is how it looks on iOS connection page prompted by system:
img_0309

Here is how it looks on iOS in safari:
img_0310

Here is how it looks on Android connection page prompted by system:
img_0312

Here is how it looks on Android in Chrome:
img_0311

As you can see here we have also the not hidden password "problem".

**Comment by blackHatMonkey** [comment]
Hi @alexsalvetti
Thanks for your contributions. After testing it on my android device it fails to show the pop up. Therefore all I get in my screen is this:

screenshot_2017-02-12-14-09-05

**Comment by alexsalvetti** [comment]
@blackHatMonkey Sorry I made a mistake and I'm trying to figure out how to solve this.. I was developing the code on stable wifiphisher 1.2 and other things have changed so my code doesn't work on the development version.

**Comment by alexsalvetti** [comment]
@blackHatMonkey @sophron Now it's fixed ;) 
My bad.. I have missed some lines of code during the merge =D

**Comment by blackHatMonkey** [comment]
@alexsalvetti I'm still unable to get the pop-up on my android device.

**Comment by alexsalvetti** [comment]
@blackHatMonkey I don't know why.. I'm using it right now and it's fully working on both iOS and Android.. I'm running the latest develompent Wifiphisher 1.2GIT with the index.html that I've modified..

**Comment by blackHatMonkey** [comment]
@alexsalvetti 
My apologies it works perfectly fine on my end now. @sophron will merge this in the next couple of day after he is done testing it. Thanks for your hard work :+1: and your :guitar: .

**Comment by alexsalvetti** [comment]
No worries @blackHatMonkey :wink: and as I said the UI can be improved for Android..
The other thing that I've not found are Windows phone and Blackberry on the Client detection system.. As this is a simple JS pop up it could work on all systems.

**Comment by blackHatMonkey** [comment]
@cicina You don't need to wait for `v1.3` if you download the git version after @sophron merges this, you could use it.

**Comment by cicina** [comment]
great thanks for your work guys and for testing. looking forward

**Comment by cicina** [comment]
guys what about Win 7? What will user see?

**Comment by alexsalvetti** [comment]
@cicina Looking at the code it should display the same windows 8/10 interface for all windows versions. I don't have a windows 7 pc to test it.

**Comment by sophron** [comment]
Thank you @alexsalvetti. :)

**Pull request merged**
