### PR TITLE
Changed logging formatting

### PR DESCRIPTION
**Pull request by leaen**
Changed colour portion of the logging output to be more consistent with
the rest of the code.

### CODE REVIEW

**Comment by 0xKD** [comment]
Only white-spaces in the *code* are being changed here, the actual logging output should remain exactly the same.

**Comment by leaen** [comment]
Pardon me, I meant how the code is formatted.

**Comment by simplyianm** [comment]
How is this consistent? Everywhere else has spaces surrounding pluses.

**Comment by sophron** [comment]
Hi @leaen,

I believe spaces make string concatenation lines easier to read. If you want to help with the coding style, you can put spaces before and after the pluses that don't have already.

**Pull request closed without merging**
