### PR TITLE
Fix issue #235

### PR DESCRIPTION
**Pull request by blackHatMonkey**
Fixes the issue #235 where the tool was unable to start. This was
due to the fact that a new version of ifconfig had come out and
the tool was outdated.

### CODE REVIEW

**Comment by sophron** [comment]
But this will break all the versions before `1.6`, correct? Why don't we support both?

**Comment by blackHatMonkey** [comment]
I just made the changes so users on kali rolling could use the tool. I will fix the actual issue in the next couple of days.

**Comment by blackHatMonkey** [comment]
Actually I just thought of a sneaky hack to make it work for both versions. I will push it when ready.

**Comment by blackHatMonkey** [comment]
Now it should work for both versions. :smile:

**Comment by sophron** [comment]
That's OK for a quick solution. We should do this properly with regex though. Thanks!

**Pull request merged**
