### PR TITLE
Critical: execv() arg 2 must contain only strings

### PR DESCRIPTION
**Pull request by HassenPy**
~Fixed: execv() arg 2 must contain only strings lines 407, 409, 412
~Fixed: variable lock referenced before assignment line 734
~Fixed: str and bool concatenation error line 750

After that the app compiled.

### CODE REVIEW

**Comment by FurqanHanif** [comment]
Not Working .. :/ 
[+] Choose the [num] of the AP you wish to copy: 2
SIOCADDRT: Network is unreachable
[*] Starting the fake access point...






















[*] M.B.A set up on channel 6 via wlan0 on False
[*] Monitor mode: wlan0 - c0:18:85:2b:xx:xx
































Jamming devices: 









DHCP Leases: 








HTTP requests: 














Jamming devices: 









DHCP Leases: 








HTTP requests: 














Jamming devices: 









DHCP Leases: 








HTTP requests: 














Jamming devices: 









DHCP Leases: 








HTTP requests: 










^C
[!] Closing
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./wifiphisher.py", line 664, in sniff_dot11
    sniff(iface=mon_iface, store=0, prn=cb)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 485, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

**Comment by HassenPy** [comment]
the problem is not originally from wifiphisher.py, it goes back to scapy, and you are actually using it on an Archlinux, it's a system error not from the app.
Please [read the requirements](https://github.com/sophron/wifiphisher#requirements)

**Comment by FurqanHanif** [comment]
i Am Getting the same error on Kali Linux , Backtrack and BackBox... :/

**Comment by sophron** [comment]
Thanks @HassenPy .

**Comment by HassenPy** [comment]
Sorry @FurqanHanif , i just took a quick look at your error,i thoght the /arch/ in the last error path had something to do with your OS.

I traced the problem , it's an exception thrown by the thread made at line 771:
    sniff_thread = Thread(target=sniff_dot11, args=(wj_iface,))
Which goes back to the sniff_dot11 function, at line 664:
    sniff(iface=mon_iface, store=0, prn=cb)
or maybe goes back to line 717:
    wj_iface = mon_iface

Which in both cases implies the use of variable mon_iface.

Now try to str(mon_iface) on each lines , try each line alone, then try the 2 lines together, if it works , please tell me so i make a pull request on it, if the problem persists , try commenting with each error log while indicating to which trial it belongs.
but please do it :pray:

@sophron , you are welcome :v:

**Pull request merged**
