### PR TITLE
Added some fluff to the standard page

### PR DESCRIPTION
**Pull request by dtoast**
Stayed with the current style (which I can change later) and just added some basic (fake) information about the "update" that is offered to the user.

### CODE REVIEW

**Comment by verdug0** [comment]
Is this a good idea for a minimal page?

**Comment by dtoast** [comment]
Well more legit looking information on the page gives it a more official feel, and it will feel more like a real update.

**Comment by jayzeng** [comment]
Should maintain a standalone changelog

**Comment by FurqanHanif** [comment]
Some Help me , How i Put Copyright in Footer??? check the code , Looks like Copyright text is define but because of some reason it's not Showing..

**Comment by sophron** [comment]
Hi @dtoast,

Is this something you have seen in a firmware upgrade page of a commercial product? We need to be very careful with what we put in the phising pages. Any information that doesn't already exist in a legit page will look suspicious.

**Comment by dtoast** [comment]
@sophron No, I just made this up. I did not want to copy exactly from a commercial update page, but if you want we could.

**Comment by sophron** [comment]
@dtoast, I'm not talking about the exact content, but the general idea of having a changelog in the update page. I believe if there aren't any routers providing a changelog, we should not include it either.

**Pull request closed without merging**
